-- Ember & Tide TCG beta schema.
-- Non-destructive setup: no DROP statements and no public RLS policies.
-- Review Row Level Security before using these tables for shared production data.

create table if not exists public.purchasers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalog_products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  brand text,
  category text,
  product_type text,
  era text,
  set_name text,
  set_code text,
  release_year integer,
  release_date date,
  msrp numeric(12, 2),
  market_value numeric(12, 2),
  market_low numeric(12, 2),
  market_mid numeric(12, 2),
  market_high numeric(12, 2),
  image_url text,
  sku text,
  upc text,
  barcode text,
  pack_count integer,
  included_packs jsonb not null default '[]'::jsonb,
  retailer_exclusive boolean not null default false,
  exclusive_retailer text,
  source_url text,
  tcgplayer_url text,
  pricecharting_url text,
  ebay_sold_url text,
  collectr_url text,
  notes text,
  status text not null default 'unknown',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  catalog_product_id uuid,
  name text not null,
  quantity integer not null default 1,
  item_count integer,
  pack_count integer,
  product_type text,
  set_name text,
  upc text,
  barcode text,
  sku text,
  purchase_price numeric(12, 2),
  total_cost numeric(12, 2),
  msrp numeric(12, 2),
  market_value numeric(12, 2),
  total_market_value numeric(12, 2),
  planned_sell_price numeric(12, 2),
  sold_price numeric(12, 2),
  fees numeric(12, 2),
  shipping numeric(12, 2),
  profit numeric(12, 2),
  profit_percentage numeric(8, 2),
  purchase_date date,
  purchase_store text,
  purchaser_id uuid,
  purchaser_name text,
  location text,
  purpose text,
  status text,
  platform text,
  listing_url text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vault_items (
  id uuid primary key default gen_random_uuid(),
  catalog_product_id uuid,
  name text not null,
  quantity integer not null default 1,
  product_type text,
  set_name text,
  upc text,
  barcode text,
  sku text,
  msrp numeric(12, 2),
  market_value numeric(12, 2),
  category text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  chain text,
  official_name text,
  nickname text,
  address text,
  city text,
  state text,
  zip text,
  phone text,
  website_url text,
  google_maps_url text,
  place_id text,
  store_type text,
  military_only boolean not null default false,
  usual_truck_days jsonb not null default '[]'::jsonb,
  usual_stock_days jsonb not null default '[]'::jsonb,
  best_time text,
  limit_policy text,
  card_location text,
  notes text,
  last_checked date,
  last_restock date,
  next_prediction date,
  prediction_confidence integer,
  prediction_reason text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.restock_reports (
  id uuid primary key default gen_random_uuid(),
  store_id uuid,
  catalog_product_id uuid,
  upc text,
  date date,
  time time,
  product_name text,
  product_category text,
  quantity_seen integer,
  quantity_remaining integer,
  stock_status text,
  report_type text,
  source text,
  source_name text,
  source_format text,
  screenshot_url text,
  extraction_confidence integer,
  user_verified_extraction boolean not null default false,
  original_text text,
  extracted_json jsonb,
  limit_info text,
  notes text,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.market_products (
  id uuid primary key default gen_random_uuid(),
  catalog_product_id uuid,
  upc text,
  name text not null,
  msrp numeric(12, 2),
  market_value numeric(12, 2),
  market_low numeric(12, 2),
  market_mid numeric(12, 2),
  market_high numeric(12, 2),
  planned_sell_price numeric(12, 2),
  source_links jsonb not null default '{}'::jsonb,
  tcgplayer_url text,
  pricecharting_url text,
  ebay_sold_url text,
  collectr_url text,
  last_updated timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deal_checks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  items jsonb not null default '[]'::jsonb,
  asking_price numeric(12, 2),
  msrp_total numeric(12, 2),
  market_total numeric(12, 2),
  percent_of_market numeric(8, 2),
  percent_of_retail numeric(8, 2),
  rating text,
  notes text,
  created_at timestamptz not null default now()
);
