export type Store = {
  id: string;
  name: string;
  country?: string;
  retailer?: string;
  storeName?: string;
  chain?: string;
  nickname?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  zipCode?: string;
  region?: string;
  phone?: string;
  storeNumber?: string;
  retailerStoreId?: string;
  latitude?: number | string | null;
  longitude?: number | string | null;
  active?: boolean;
  pokemonStockLikelihood?: string;
  source?: string;
  sourceUrl?: string;
  lastVerifiedAt?: string;
  verifiedBy?: string;
  confidence?: string;
  website?: string;
  storeType?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
};

export type StoreReport = {
  id: string;
  storeId?: string;
  storeName?: string;
  chain?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  reportDate?: string;
  reportTime?: string;
  reportedBy?: string;
  productName?: string;
  productType?: string;
  quantitySeen?: number | null;
  price?: number | null;
  shelfLocation?: string;
  limits?: string;
  notes?: string;
  photoUrl?: string;
  confidenceLevel?: string;
  verified?: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ScoutAlert = {
  id: string;
  title: string;
  message?: string;
  type?: string;
  enabled?: boolean;
  createdAt: string;
  updatedAt: string;
};
