export const ACCOUNT_OPS_STORAGE_KEY = "code3.account-ops.v1";
export const ACCOUNT_OPS_SCHEMA_VERSION = 1;

export const ACCOUNT_OPS_COLLECTIONS = Object.freeze([
  "profileGroups",
  "profiles",
  "emailDomains",
  "emailAliases",
  "retailers",
  "storeAccounts",
  "tasks",
  "activity",
]);

export const RECORD_STATUS = Object.freeze({ ACTIVE: "ACTIVE", ARCHIVED: "ARCHIVED" });

export const EMAIL_DOMAIN_MODES = Object.freeze({
  LOCAL_METADATA_ONLY: "LOCAL_METADATA_ONLY",
  CATCH_ALL: "CATCH_ALL",
  PROVIDER_MANAGED: "PROVIDER_MANAGED",
});

export const EMAIL_DOMAIN_STATUSES = Object.freeze({
  NOT_CONFIGURED: "NOT_CONFIGURED",
  CONFIGURED: "CONFIGURED",
  OWNER_CONFIRMED: "OWNER_CONFIRMED",
  ERROR: "ERROR",
  ARCHIVED: "ARCHIVED",
});

export const EMAIL_ALIAS_STATUSES = Object.freeze({
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  DISABLED: "DISABLED",
  ERROR: "ERROR",
  ARCHIVED: "ARCHIVED",
});

export const ALIAS_PROVISIONING_STATES = Object.freeze({
  GENERATED_LOCAL: "GENERATED_LOCAL",
  CATCH_ALL_DECLARED: "CATCH_ALL_DECLARED",
  PROVIDER_PROVISIONED: "PROVIDER_PROVISIONED",
  RECEIVING_CONFIRMED: "RECEIVING_CONFIRMED",
  FAILED: "FAILED",
});

export const VERIFICATION_STATES = Object.freeze({
  UNKNOWN: "UNKNOWN",
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  NOT_REQUIRED: "NOT_REQUIRED",
  FAILED: "FAILED",
});

export const STORE_ACCOUNT_STATUSES = Object.freeze({
  SETUP: "SETUP",
  NEEDS_VERIFICATION: "NEEDS_VERIFICATION",
  READY: "READY",
  NEEDS_ATTENTION: "NEEDS_ATTENTION",
  LOCKED: "LOCKED",
  DISABLED: "DISABLED",
  ARCHIVED: "ARCHIVED",
});

export const ACCOUNT_SETUP_STAGES = Object.freeze({
  PREPARED: "PREPARED",
  SIGNUP_OPENED: "SIGNUP_OPENED",
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
  PHONE_VERIFICATION: "PHONE_VERIFICATION",
  OWNER_CONFIRMATION: "OWNER_CONFIRMATION",
  READY: "READY",
});

export const ACCOUNT_HEALTH_STATES = Object.freeze({
  HEALTHY: "HEALTHY",
  NEEDS_ATTENTION: "NEEDS_ATTENTION",
  PROBLEM: "PROBLEM",
  UNKNOWN: "UNKNOWN",
});

export const CREDENTIAL_REFERENCE_PROVIDERS = Object.freeze({
  EXTERNAL_PASSWORD_MANAGER: "EXTERNAL_PASSWORD_MANAGER",
  OS_SECURE_STORE: "OS_SECURE_STORE",
  UNAVAILABLE: "UNAVAILABLE",
});

export const ACCOUNT_TASK_TYPES = Object.freeze({
  VERIFY_EMAIL: "VERIFY_EMAIL",
  VERIFY_PHONE: "VERIFY_PHONE",
  COMPLETE_SETUP: "COMPLETE_SETUP",
  PASSWORD_RESET: "PASSWORD_RESET",
  SECURITY_REVIEW: "SECURITY_REVIEW",
  ACCOUNT_PROBLEM: "ACCOUNT_PROBLEM",
  CHECK_ORDER: "CHECK_ORDER",
  PICKUP_DEADLINE: "PICKUP_DEADLINE",
  RETURN_DEADLINE: "RETURN_DEADLINE",
  REFUND_FOLLOWUP: "REFUND_FOLLOWUP",
  CUSTOM: "CUSTOM",
});

export const ACCOUNT_TASK_STATUSES = Object.freeze({ OPEN: "OPEN", DONE: "DONE", DISMISSED: "DISMISSED", ARCHIVED: "ARCHIVED" });
export const ACCOUNT_TASK_PRIORITIES = Object.freeze({ LOW: "LOW", NORMAL: "NORMAL", HIGH: "HIGH", URGENT: "URGENT" });

export const ACCOUNT_OPS_PROVENANCE = Object.freeze({
  OWNER_ENTERED: "OWNER_ENTERED",
  GENERATED_LOCAL: "GENERATED_LOCAL",
  PROVIDER_SUPPLIED: "PROVIDER_SUPPLIED",
  SYSTEM_DERIVED: "SYSTEM_DERIVED",
});

export const ACCOUNT_OPS_LIMITS = Object.freeze({
  maximumText: 4_000,
  maximumNotes: 16_000,
  maximumRecordsPerCollection: 5_000,
  maximumAliasAttempts: 64,
  minimumPasswordLength: 16,
  maximumPasswordLength: 128,
});
