export const ACCOUNTANT_REVIEW_FORMAT = "code3.accountant-review-preview.v1";

export const ACCOUNTANT_REVIEW_CATEGORIES = Object.freeze({
  PRIOR_PERIOD_COGS_ADJUSTMENT: "PRIOR_PERIOD_COGS_ADJUSTMENT",
  CURRENT_PERIOD_COGS_ADJUSTMENT: "CURRENT_PERIOD_COGS_ADJUSTMENT",
  PRODUCT_RECLASSIFICATION_REVIEW: "PRODUCT_RECLASSIFICATION_REVIEW",
  INVENTORY_COST_REVIEW: "INVENTORY_COST_REVIEW",
  REFUND_ACCOUNTING_REVIEW: "REFUND_ACCOUNTING_REVIEW",
  RETURN_ACCOUNTING_REVIEW: "RETURN_ACCOUNTING_REVIEW",
  RECONCILIATION_REVERSAL_REVIEW: "RECONCILIATION_REVERSAL_REVIEW",
  SALE_REPORTING_REVIEW: "SALE_REPORTING_REVIEW",
  TRANSFER_REVIEW_BLOCKED: "TRANSFER_REVIEW_BLOCKED",
});

export const ACCOUNTANT_REVIEW_SEVERITIES = Object.freeze({
  INFO: "INFO",
  REVIEW: "REVIEW",
  HIGH_ATTENTION: "HIGH_ATTENTION",
});

export const ACCOUNTANT_REVIEW_PERIOD_FLAGS = Object.freeze({
  NO_PRIOR_PERIOD_ISSUE: "NO_PRIOR_PERIOD_ISSUE",
  SAME_MONTH_ADJUSTMENT: "SAME_MONTH_ADJUSTMENT",
  SAME_QUARTER_ADJUSTMENT: "SAME_QUARTER_ADJUSTMENT",
  PRIOR_MONTH_REVIEW: "PRIOR_MONTH_REVIEW",
  PRIOR_QUARTER_REVIEW: "PRIOR_QUARTER_REVIEW",
  PRIOR_YEAR_REVIEW: "PRIOR_YEAR_REVIEW",
  ACCOUNTANT_REVIEW_RECOMMENDED: "ACCOUNTANT_REVIEW_RECOMMENDED",
});

export const ACCOUNTANT_REVIEW_FILING_STATUSES = Object.freeze({
  UNKNOWN: "FILING_STATUS_UNKNOWN",
});

export const ACCOUNTANT_REVIEW_MOVEMENT_TYPES = Object.freeze({
  NONE: "NONE",
  REFUND_ONLY: "REFUND_ONLY",
  RETURN_ONLY: "RETURN_ONLY",
  REFUND_AND_RETURN: "REFUND_AND_RETURN",
  PARTIAL_REFUND: "PARTIAL_REFUND",
  PARTIAL_RETURN: "PARTIAL_RETURN",
});

export const ACCOUNTANT_REVIEW_GRANULARITIES = Object.freeze({
  MONTH: "MONTH",
  QUARTER: "QUARTER",
  YEAR: "YEAR",
});

export const ACCOUNTANT_REVIEW_FILTER_FIELDS = Object.freeze([
  "year",
  "quarter",
  "month",
  "retailer",
  "productReference",
  "saleId",
  "category",
  "severity",
]);

export const ACCOUNTANT_REVIEW_SAFETY = Object.freeze({
  authoritative: false,
  persisted: false,
  readOnly: true,
  createsAccountingLedger: false,
  postsJournalEntries: false,
  mutatesHistoricalSales: false,
  mutatesHistoricalCogs: false,
  mutatesPurchases: false,
  mutatesInventory: false,
  mutatesTransfers: false,
  infersTaxTreatment: false,
  filingStatus: ACCOUNTANT_REVIEW_FILING_STATUSES.UNKNOWN,
  remoteActive: false,
});
