export const INVENTORY_CORRECTION_CANDIDATE_FORMAT = "code3.inventory-correction-candidate.v1";

export const INVENTORY_CORRECTION_CATEGORIES = Object.freeze({
  CREATION_REVERSAL: "CREATION_REVERSAL",
  PRODUCT_RESOLUTION_CORRECTION: "PRODUCT_RESOLUTION_CORRECTION",
  CONDITION_CORRECTION: "CONDITION_CORRECTION",
  QUANTITY_CORRECTION: "QUANTITY_CORRECTION",
  RETURN_TO_RETAILER: "RETURN_TO_RETAILER",
  PARTIAL_RETURN: "PARTIAL_RETURN",
  DAMAGED_AFTER_RECEIVING: "DAMAGED_AFTER_RECEIVING",
  WRONG_ITEM_RESOLUTION: "WRONG_ITEM_RESOLUTION",
  SUBSTITUTION_RESOLUTION: "SUBSTITUTION_RESOLUTION",
  REPLACEMENT_RECEIVED: "REPLACEMENT_RECEIVED",
  UNEXPECTED_EXTRA_RESOLUTION: "UNEXPECTED_EXTRA_RESOLUTION",
  ACQUISITION_COST_CORRECTION: "ACQUISITION_COST_CORRECTION",
  REVERSAL_CORRECTION: "REVERSAL_CORRECTION",
});

export const INVENTORY_CORRECTION_EVENT_KINDS = Object.freeze({
  CORRECTION: "INVENTORY_CORRECTION_EVENT",
  DISPOSITION: "INVENTORY_DISPOSITION_EVENT",
  REVERSAL: "INVENTORY_REVERSAL_EVENT",
});

export const INVENTORY_CORRECTION_DISPOSITIONS = Object.freeze({
  AVAILABLE: "AVAILABLE",
  DAMAGED: "DAMAGED",
  HOLD_FOR_RETURN: "HOLD_FOR_RETURN",
  RETURNED: "RETURNED",
  LOST: "LOST",
  DISPOSED: "DISPOSED",
  REPLACED: "REPLACED",
  CORRECTION_PENDING: "CORRECTION_PENDING",
});

export const INVENTORY_QUANTITY_CORRECTION_REASONS = Object.freeze({
  COUNT_CORRECTION: "COUNT_CORRECTION",
  RETURN: "RETURN",
  DAMAGE_DISPOSITION: "DAMAGE_DISPOSITION",
  LOSS: "LOSS",
  FOUND_EXTRA: "FOUND_EXTRA",
  REVERSAL_REPAIR: "REVERSAL_REPAIR",
});

export const INVENTORY_EXTRA_COST_TREATMENTS = Object.freeze({
  ZERO_COST_CONFIRMED: "ZERO_COST_CONFIRMED",
  ALLOCATED_COST: "ALLOCATED_COST",
  MANUAL_COST: "MANUAL_COST",
  UNKNOWN_COST_BLOCKED: "UNKNOWN_COST_BLOCKED",
});

export const INVENTORY_CORRECTION_LIMITS = Object.freeze({
  maximumIdentifier: 500,
  maximumReason: 1_000,
  maximumQuantity: 1_000_000,
  maximumWarnings: 100,
});

export const INVENTORY_CORRECTION_SAFETY = Object.freeze({
  authoritative: "LOCAL_ONLY",
  remoteActive: false,
  ownerConfirmationRequired: true,
  candidatePersisted: false,
  candidateEqualsMutation: false,
  automaticReplacementInventory: false,
  automaticProductCreation: false,
  refundRemovesInventory: false,
  originalHistoryMutable: false,
  serverGradeTransactionsActive: false,
});

export const INVENTORY_CORRECTION_BLOCKED_CATEGORIES = Object.freeze([
  INVENTORY_CORRECTION_CATEGORIES.REPLACEMENT_RECEIVED,
  INVENTORY_CORRECTION_CATEGORIES.UNEXPECTED_EXTRA_RESOLUTION,
]);
