export const INVENTORY_RECONCILIATION_FORMAT = "code3.inventory-reconciliation.v1";
export const INVENTORY_RECONCILIATION_CANDIDATE_FORMAT = "code3.inventory-reconciliation-candidate.v1";

export const INVENTORY_RECONCILIATION_CATEGORIES = Object.freeze({
  COGS_RECONCILIATION: "COGS_RECONCILIATION",
  SALE_PRODUCT_RECONCILIATION: "SALE_PRODUCT_RECONCILIATION",
  SALE_COST_RECONCILIATION: "SALE_COST_RECONCILIATION",
  TRANSFER_PRODUCT_RECONCILIATION: "TRANSFER_PRODUCT_RECONCILIATION",
  TRANSFER_COST_RECONCILIATION: "TRANSFER_COST_RECONCILIATION",
  TRANSFER_PROVENANCE_RECONCILIATION: "TRANSFER_PROVENANCE_RECONCILIATION",
  RETURN_AFTER_SALE_RECONCILIATION: "RETURN_AFTER_SALE_RECONCILIATION",
  LOT_PROVENANCE_RECONCILIATION: "LOT_PROVENANCE_RECONCILIATION",
  PRIOR_CORRECTION_REVERSAL: "PRIOR_CORRECTION_REVERSAL",
  ACCOUNTING_ADJUSTMENT: "ACCOUNTING_ADJUSTMENT",
});

export const INVENTORY_RECONCILIATION_STATUSES = Object.freeze({
  DRAFT: "DRAFT",
  NEEDS_REVIEW: "NEEDS_REVIEW",
  BLOCKED: "BLOCKED",
  READY_TO_CONFIRM: "READY_TO_CONFIRM",
  CONFIRMED: "CONFIRMED",
  REVERSED: "REVERSED",
});

export const INVENTORY_RECONCILIATION_EVENT_TYPES = Object.freeze({
  INVENTORY: "INVENTORY_RECONCILIATION_EVENT",
  SALE: "SALE_RECONCILIATION_EVENT",
  TRANSFER: "TRANSFER_RECONCILIATION_EVENT",
  ACCOUNTING: "ACCOUNTING_ADJUSTMENT_EVENT",
});

export const INVENTORY_RECONCILIATION_LIMITS = Object.freeze({
  maximumIdentifier: 500,
  maximumReason: 1_000,
  maximumQuantity: 1_000_000,
  maximumAffectedSales: 10_000,
  maximumAffectedTransfers: 1_000,
});

export const INVENTORY_RECONCILIATION_SAFETY = Object.freeze({
  authoritative: "LOCAL_ONLY",
  remoteActive: false,
  ownerConfirmationRequired: true,
  candidatePersisted: false,
  candidateEqualsHistoricalMutation: false,
  originalSalesMutable: false,
  originalTransfersMutable: false,
  realizedCogsDestructivelyRewritten: false,
  remoteTransactionsActive: false,
});

export const TRANSFER_RECONCILIATION_CATEGORIES = Object.freeze([
  INVENTORY_RECONCILIATION_CATEGORIES.TRANSFER_PRODUCT_RECONCILIATION,
  INVENTORY_RECONCILIATION_CATEGORIES.TRANSFER_COST_RECONCILIATION,
  INVENTORY_RECONCILIATION_CATEGORIES.TRANSFER_PROVENANCE_RECONCILIATION,
]);

export const COST_RECONCILIATION_CATEGORIES = Object.freeze([
  INVENTORY_RECONCILIATION_CATEGORIES.COGS_RECONCILIATION,
  INVENTORY_RECONCILIATION_CATEGORIES.SALE_COST_RECONCILIATION,
  INVENTORY_RECONCILIATION_CATEGORIES.ACCOUNTING_ADJUSTMENT,
]);
