export const INTELLIGENCE_CONFIDENCE = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  INSUFFICIENT: "INSUFFICIENT",
});

export const EVIDENCE_PROVENANCE = Object.freeze({
  MACHINE_OBSERVED: "MACHINE_OBSERVED",
  PROVIDER_SUPPLIED: "PROVIDER_SUPPLIED",
  OWNER_ENTERED: "OWNER_ENTERED",
  INFERRED: "INFERRED",
});

export const CARD_CONDITION = Object.freeze({
  NM: "NM",
  LP: "LP",
  MP: "MP",
  HP: "HP",
  DMG: "DMG",
});

export const CARD_FORMAT = Object.freeze({
  RAW: "RAW",
  SLABBED: "SLABBED",
  UNKNOWN: "UNKNOWN",
});

export const IMAGE_SIDE = Object.freeze({
  FRONT: "FRONT",
  BACK: "BACK",
  OTHER: "OTHER",
  UNKNOWN: "UNKNOWN",
});

export const DEFECT_SEVERITY = Object.freeze({
  MINOR: "MINOR",
  MODERATE: "MODERATE",
  SEVERE: "SEVERE",
  CRITICAL: "CRITICAL",
  UNKNOWN: "UNKNOWN",
});

export const DEFECT_TYPE = Object.freeze({
  WHITENING: "WHITENING",
  EDGE_WEAR: "EDGE_WEAR",
  CORNER_WEAR: "CORNER_WEAR",
  SURFACE_SCRATCHES: "SURFACE_SCRATCHES",
  DENTS: "DENTS",
  CREASES: "CREASES",
  FOLDS: "FOLDS",
  TEARS: "TEARS",
  CUTS: "CUTS",
  PEELING: "PEELING",
  STAINING: "STAINING",
  INK_OR_WRITING: "INK_OR_WRITING",
  WATER_OR_LIQUID_DAMAGE: "WATER_OR_LIQUID_DAMAGE",
  WARPING: "WARPING",
  PRINT_DEFECTS: "PRINT_DEFECTS",
  BINDER_DENTS: "BINDER_DENTS",
  PRESSURE_MARKS: "PRESSURE_MARKS",
  HOLO_SCRATCHING: "HOLO_SCRATCHING",
  CENTERING_OBSERVATION: "CENTERING_OBSERVATION",
  MISSING_MATERIAL: "MISSING_MATERIAL",
  UNKNOWN_OR_UNVERIFIABLE: "UNKNOWN_OR_UNVERIFIABLE",
});

export const VALUE_EVIDENCE_TYPE = Object.freeze({
  SOLD_COMPARABLE: "SOLD_COMPARABLE",
  ACTIVE_LISTING: "ACTIVE_LISTING",
  REFERENCE_PRICE: "REFERENCE_PRICE",
  OWNER_COST: "OWNER_COST",
  OWNER_SALE: "OWNER_SALE",
  PREDICTED_RESALE: "PREDICTED_RESALE",
});

export const DEAL_RECOMMENDATION = Object.freeze({
  STRONG_BUY: "STRONG_BUY",
  BUY: "BUY",
  WATCH: "WATCH",
  PASS: "PASS",
  INSUFFICIENT_DATA: "INSUFFICIENT_DATA",
});

export const RESTOCK_LIKELIHOOD = Object.freeze({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  INSUFFICIENT: "INSUFFICIENT",
});

export const RESTOCK_OBSERVATION_TYPE = Object.freeze({
  STOCK_OBSERVED: "STOCK_OBSERVED",
  EMPTY_SHELF: "EMPTY_SHELF",
  RESTOCK_EVIDENCE: "RESTOCK_EVIDENCE",
  VISIT_SUCCESS: "VISIT_SUCCESS",
  VISIT_UNSUCCESSFUL: "VISIT_UNSUCCESSFUL",
});

export const LOT_ITEM_CERTAINTY = Object.freeze({
  IDENTIFIED: "IDENTIFIED",
  PROBABLE: "PROBABLE",
  UNKNOWN: "UNKNOWN",
});

export const ANALYSIS_METHODOLOGY = Object.freeze({
  CARD: "code3.card-analysis.v1",
  CONDITION: "code3.condition-rules.v1",
  VALUATION: "code3.valuation.v2",
  DEAL: "code3.deal-intelligence.v1",
  AUCTION: "code3.auction-intelligence.v1",
  LOT: "code3.lot-intelligence.v1",
  RESTOCK: "code3.restock-intelligence.v1",
});

export const ALL_INTELLIGENCE_CONFIDENCE = Object.freeze(Object.values(INTELLIGENCE_CONFIDENCE));
export const ALL_EVIDENCE_PROVENANCE = Object.freeze(Object.values(EVIDENCE_PROVENANCE));
export const ALL_CARD_CONDITIONS = Object.freeze(Object.values(CARD_CONDITION));
export const ALL_DEFECT_TYPES = Object.freeze(Object.values(DEFECT_TYPE));
export const ALL_VALUE_EVIDENCE_TYPES = Object.freeze(Object.values(VALUE_EVIDENCE_TYPE));
