export const BOT_OPS_STORAGE_KEY = "code3.bot-ops.v1";
export const BOT_OPS_SCHEMA_VERSION = 1;
export const BOT_OPS_FORMAT = "code3.bot-ops.v1";
export const BOT_OPS_PROCESSING_VERSION = "code3.bot-event-normalization.v1";

export const BOT_OPS_COLLECTIONS = Object.freeze([
  "installations",
  "retailerAccountLinks",
  "botProfiles",
  "proxyGroups",
  "productTargets",
  "taskGroups",
  "tasks",
  "attempts",
  "checkoutEvidence",
  "activity",
]);

export const BOT_PROVIDER_KEYS = Object.freeze({ HAYHA: "HAYHA", STELLAR: "STELLAR", MOCK: "MOCK" });

export const BOT_PROVIDER_CONNECTION_STATUS = Object.freeze({
  NOT_CONFIGURED: "NOT_CONFIGURED",
  DISCONNECTED: "DISCONNECTED",
  CONNECTING: "CONNECTING",
  CONNECTED: "CONNECTED",
  NEEDS_ATTENTION: "NEEDS_ATTENTION",
  ERROR: "ERROR",
  DISABLED: "DISABLED",
});

export const BOT_INTEGRATION_MODES = Object.freeze({
  OFFICIAL_API: "OFFICIAL_API",
  LOCAL_COMPANION: "LOCAL_COMPANION",
  EXPORTED_DATA: "EXPORTED_DATA",
  WEBHOOK_EVENT: "WEBHOOK_EVENT",
  OWNER_APPROVED_LOCAL_AUTOMATION: "OWNER_APPROVED_LOCAL_AUTOMATION",
  TEST_ONLY_MOCK: "TEST_ONLY_MOCK",
});

// Phase 2D-B1 discovery metadata is intentionally separate from the persisted
// installation schema above. Documentation evidence must never enable a live
// adapter or broaden an installation capability snapshot.
export const BOT_DISCOVERY_CAPABILITIES = Object.freeze({
  OBSERVE_RUNTIME: "OBSERVE_RUNTIME",
  READ_TASK_GROUPS: "READ_TASK_GROUPS",
  READ_TASKS: "READ_TASKS",
  READ_STATUS: "READ_STATUS",
  READ_HISTORY: "READ_HISTORY",
  READ_CHECKOUT_EVIDENCE: "READ_CHECKOUT_EVIDENCE",
  CREATE_TASK: "CREATE_TASK",
  EDIT_TASK: "EDIT_TASK",
  START_TASK: "START_TASK",
  STOP_TASK: "STOP_TASK",
  RESTART_TASK: "RESTART_TASK",
  READ_ACCOUNT_METADATA: "READ_ACCOUNT_METADATA",
  READ_PROXY_METADATA: "READ_PROXY_METADATA",
  READ_PROFILE_METADATA: "READ_PROFILE_METADATA",
});

export const BOT_DISCOVERY_INTEGRATION_MODES = Object.freeze({
  OFFICIAL_API: "OFFICIAL_API",
  DOCUMENTED_WEBHOOK: "DOCUMENTED_WEBHOOK",
  DOCUMENTED_EXPORT: "DOCUMENTED_EXPORT",
  DOCUMENTED_LOCAL_INTERFACE: "DOCUMENTED_LOCAL_INTERFACE",
  SUPPORTED_PLUGIN: "SUPPORTED_PLUGIN",
  OWNER_FILE_IMPORT: "OWNER_FILE_IMPORT",
  LOCAL_READ_ONLY_COMPANION: "LOCAL_READ_ONLY_COMPANION",
  MANUAL_IMPORT: "MANUAL_IMPORT",
  UNSUPPORTED_PRIVATE_API: "UNSUPPORTED_PRIVATE_API",
  REVERSE_ENGINEERED_INTERFACE: "REVERSE_ENGINEERED_INTERFACE",
});

export const BOT_EVIDENCE_STATUSES = Object.freeze({
  VERIFIED_SUPPORTED: "VERIFIED_SUPPORTED",
  DOCUMENTED_BUT_LIMITED: "DOCUMENTED_BUT_LIMITED",
  UNKNOWN: "UNKNOWN",
  UNSUPPORTED: "UNSUPPORTED",
  DO_NOT_USE: "DO_NOT_USE",
});

export const BOT_PILOT_READINESS = Object.freeze({
  NO_LIVE_BOT_PILOT_YET: "NO_LIVE_BOT_PILOT_YET",
  OFFLINE_REVIEW_CANDIDATE: "OFFLINE_REVIEW_CANDIDATE",
  ELIGIBLE_FOR_SEPARATE_AUTHORIZATION: "ELIGIBLE_FOR_SEPARATE_AUTHORIZATION",
});

export const BOT_CAPABILITIES = Object.freeze({
  RUNTIME_HEALTH: "RUNTIME_HEALTH",
  RETAILER_DISCOVERY: "RETAILER_DISCOVERY",
  TASK_DISCOVERY: "TASK_DISCOVERY",
  TASK_STATUS: "TASK_STATUS",
  START_TASK: "START_TASK",
  STOP_TASK: "STOP_TASK",
  RESTART_TASK: "RESTART_TASK",
  ACCOUNT_PROFILE_MAPPING: "ACCOUNT_PROFILE_MAPPING",
  PROXY_ASSIGNMENT_VISIBILITY: "PROXY_ASSIGNMENT_VISIBILITY",
  PRODUCT_TARGET_VISIBILITY: "PRODUCT_TARGET_VISIBILITY",
  CHECKOUT_EVIDENCE: "CHECKOUT_EVIDENCE",
  EVENT_HISTORY: "EVENT_HISTORY",
});

export const BOT_INSTALLATION_HEALTH = Object.freeze({
  UNKNOWN: "UNKNOWN",
  HEALTHY: "HEALTHY",
  DEGRADED: "DEGRADED",
  DISCONNECTED: "DISCONNECTED",
  ERROR: "ERROR",
  DISABLED: "DISABLED",
});

export const BOT_RECORD_STATUS = Object.freeze({ ACTIVE: "ACTIVE", DISABLED: "DISABLED", ARCHIVED: "ARCHIVED" });

export const BOT_TASK_STATUSES = Object.freeze({
  DRAFT: "DRAFT",
  READY: "READY",
  RUNNING: "RUNNING",
  PAUSED: "PAUSED",
  STOPPED: "STOPPED",
  WAITING: "WAITING",
  MONITORING: "MONITORING",
  CARTED: "CARTED",
  CHECKOUT_ATTEMPT: "CHECKOUT_ATTEMPT",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  ACCOUNT_ERROR: "ACCOUNT_ERROR",
  PROXY_ERROR: "PROXY_ERROR",
  PAYMENT_ERROR: "PAYMENT_ERROR",
  RETAILER_BLOCK: "RETAILER_BLOCK",
  UNKNOWN: "UNKNOWN",
});

export const BOT_TASK_MODES = Object.freeze({
  MANUAL_DRAFT: "MANUAL_DRAFT",
  MONITOR: "MONITOR",
  RESTOCK: "RESTOCK",
  RELEASE: "RELEASE",
  UNKNOWN: "UNKNOWN",
});

export const BOT_SCHEDULE_MODES = Object.freeze({ MANUAL: "MANUAL", PROVIDER_DEFINED: "PROVIDER_DEFINED", UNKNOWN: "UNKNOWN" });

export const BOT_PROXY_TYPES = Object.freeze({
  DATACENTER: "DATACENTER",
  RESIDENTIAL: "RESIDENTIAL",
  ISP: "ISP",
  MOBILE: "MOBILE",
  UNKNOWN: "UNKNOWN",
});

export const BOT_PROXY_HEALTH = Object.freeze({
  UNKNOWN: "UNKNOWN",
  HEALTHY: "HEALTHY",
  DEGRADED: "DEGRADED",
  ERROR: "ERROR",
  DISABLED: "DISABLED",
});

export const BOT_ATTEMPT_EVENTS = Object.freeze({
  STATUS_OBSERVED: "STATUS_OBSERVED",
  TASK_WAITING: "TASK_WAITING",
  TASK_MONITORING: "TASK_MONITORING",
  CARTED: "CARTED",
  CHECKOUT_ATTEMPT: "CHECKOUT_ATTEMPT",
  CHECKOUT_SUCCEEDED: "CHECKOUT_SUCCEEDED",
  CHECKOUT_FAILED: "CHECKOUT_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  ACCOUNT_ERROR: "ACCOUNT_ERROR",
  PROXY_ERROR: "PROXY_ERROR",
  PAYMENT_ERROR: "PAYMENT_ERROR",
  RETAILER_BLOCK: "RETAILER_BLOCK",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  UNKNOWN: "UNKNOWN",
});

export const BOT_FAILURE_CATEGORIES = Object.freeze({
  NONE: "NONE",
  ACCOUNT: "ACCOUNT",
  PROXY: "PROXY",
  PAYMENT: "PAYMENT",
  RATE_LIMIT: "RATE_LIMIT",
  RETAILER_BLOCK: "RETAILER_BLOCK",
  PROVIDER: "PROVIDER",
  VALIDATION: "VALIDATION",
  UNKNOWN: "UNKNOWN",
});

export const BOT_EVIDENCE_REVIEW_STATES = Object.freeze({
  NEW: "NEW",
  NEEDS_REVIEW: "NEEDS_REVIEW",
  CONFIRMED: "CONFIRMED",
  CORRECTED: "CORRECTED",
  REJECTED: "REJECTED",
  RECONCILED: "RECONCILED",
});

export const BOT_PROVENANCE = Object.freeze({
  OWNER_ENTERED: "OWNER_ENTERED",
  PROVIDER_NORMALIZED: "PROVIDER_NORMALIZED",
  SYSTEM_DERIVED: "SYSTEM_DERIVED",
  TEST_FIXTURE: "TEST_FIXTURE",
});

export const BOT_OPS_LIMITS = Object.freeze({
  maximumString: 4_000,
  maximumNotes: 16_000,
  maximumWarnings: 100,
  maximumRecordsPerCollection: 5_000,
  maximumDepth: 16,
  maximumNodes: 10_000,
  maximumArray: 1_000,
});

export const BOT_OPS_PERSISTENCE_CONTRACT = Object.freeze({
  storageKey: BOT_OPS_STORAGE_KEY,
  schemaVersion: BOT_OPS_SCHEMA_VERSION,
  collections: BOT_OPS_COLLECTIONS,
  authoritativeMode: "LOCAL_ONLY",
  remoteActive: false,
  liveProviderConnections: false,
  providerNetworkAccess: false,
  automaticTaskControl: false,
  automaticCheckout: false,
  automaticPurchaseCreation: false,
  automaticReceiving: false,
  automaticInventoryMutation: false,
  botSuccessEqualsPurchase: false,
  checkoutEvidenceEqualsPurchase: false,
  localSecretPersistence: false,
});
