import { EVIDENCE_PROVENANCE, INTELLIGENCE_CONFIDENCE } from "../intelligence/constants.js";

export const INBOX_ORDER_STORAGE_KEY = "code3.inbox-order.v1";
export const INBOX_ORDER_SCHEMA_VERSION = 1;
export const INBOX_ORDER_FORMAT = "code3.inbox-order.v1";
export const INBOX_ORDER_PROCESSING_VERSION = "code3.inbox-order-normalization.v1";

export const INBOX_ORDER_COLLECTIONS = Object.freeze([
  "messageEvents",
  "orderCandidates",
  "candidateEvents",
  "activity",
]);

export const MESSAGE_CATEGORIES = Object.freeze({
  VERIFICATION: "VERIFICATION",
  ORDER_CONFIRMATION: "ORDER_CONFIRMATION",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  REFUND: "REFUND",
  RETURN: "RETURN",
  PICKUP: "PICKUP",
  PASSWORD_SECURITY: "PASSWORD_SECURITY",
  RETAILER_NOTICE: "RETAILER_NOTICE",
  OTHER: "OTHER",
  PROTECTED: "PROTECTED",
});

export const ORDER_RELATED_CATEGORIES = Object.freeze(new Set([
  MESSAGE_CATEGORIES.ORDER_CONFIRMATION,
  MESSAGE_CATEGORIES.SHIPPED,
  MESSAGE_CATEGORIES.DELIVERED,
  MESSAGE_CATEGORIES.CANCELLED,
  MESSAGE_CATEGORIES.REFUND,
  MESSAGE_CATEGORIES.RETURN,
  MESSAGE_CATEGORIES.PICKUP,
]));

export const ORDER_STATES = Object.freeze({
  DETECTED: "DETECTED",
  CONFIRMED: "CONFIRMED",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  PARTIALLY_SHIPPED: "PARTIALLY_SHIPPED",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  PARTIALLY_CANCELLED: "PARTIALLY_CANCELLED",
  RETURNED: "RETURNED",
  REFUNDED: "REFUNDED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
  UNKNOWN: "UNKNOWN",
});

export const ORDER_REVIEW_STATES = Object.freeze({
  NEW: "NEW",
  NEEDS_REVIEW: "NEEDS_REVIEW",
  CONFIRMED: "CONFIRMED",
  CORRECTED: "CORRECTED",
  REJECTED: "REJECTED",
  IMPORTED_FUTURE: "IMPORTED_FUTURE",
});

export const PROVIDER_HEALTH_STATES = Object.freeze({
  DISCONNECTED: "DISCONNECTED",
  CONNECTING: "CONNECTING",
  HEALTHY: "HEALTHY",
  NEEDS_REAUTH: "NEEDS_REAUTH",
  ERROR: "ERROR",
  REVOKED: "REVOKED",
});

export const FULFILLMENT_TYPES = Object.freeze({
  SHIPPING: "SHIPPING",
  PICKUP: "PICKUP",
  DIGITAL: "DIGITAL",
  UNKNOWN: "UNKNOWN",
});

export const MESSAGE_RETENTION = Object.freeze({
  STRUCTURED_METADATA: "STRUCTURED_METADATA",
  PROTECTED_MINIMUM: "PROTECTED_MINIMUM",
  DISCARDED_AFTER_CLASSIFICATION: "DISCARDED_AFTER_CLASSIFICATION",
});

export const CANDIDATE_EVENT_TYPES = Object.freeze({
  DETECTED: "DETECTED",
  SOURCE_EVENT_ADDED: "SOURCE_EVENT_ADDED",
  SOURCE_EVENT_REVISED: "SOURCE_EVENT_REVISED",
  OWNER_CONFIRMED: "OWNER_CONFIRMED",
  OWNER_CORRECTED: "OWNER_CORRECTED",
  OWNER_REJECTED: "OWNER_REJECTED",
});

export const INBOX_ORDER_LIMITS = Object.freeze({
  maximumString: 4_000,
  maximumSubject: 500,
  maximumRecordsPerCollection: 5_000,
  maximumLineItems: 250,
  maximumRecipients: 50,
  maximumTrackingReferences: 50,
  maximumWarnings: 100,
  maximumDepth: 16,
  maximumNodes: 10_000,
});

export const INBOX_ORDER_CONFIDENCE = INTELLIGENCE_CONFIDENCE;
export const INBOX_ORDER_PROVENANCE = EVIDENCE_PROVENANCE;

export const INBOX_ORDER_PERSISTENCE_CONTRACT = Object.freeze({
  storageKey: INBOX_ORDER_STORAGE_KEY,
  schemaVersion: INBOX_ORDER_SCHEMA_VERSION,
  collections: INBOX_ORDER_COLLECTIONS,
  authoritativeMode: "LOCAL_ONLY",
  remoteActive: false,
  automaticPurchaseCreation: false,
  rawMessageBodyPersistence: false,
  providerSecretPersistence: false,
});
