export const INVENTORY_CREATION_FORMAT = "code3.inventory-creation.v1";

export const INVENTORY_CREATION_APPLICATION_STATES = Object.freeze({
  PREPARED: "PREPARED",
  COMPLETED: "COMPLETED",
  REVERSED: "REVERSED",
});

export const INVENTORY_CREATION_EVENT_TYPES = Object.freeze({
  INVENTORY_CREATED: "INVENTORY_CREATED",
  INVENTORY_REVERSED: "INVENTORY_REVERSED",
  PRODUCT_RESOLUTION_CORRECTED: "PRODUCT_RESOLUTION_CORRECTED",
});

export const INVENTORY_ADJUSTMENT_TYPES = Object.freeze({
  CREATION_REVERSAL: "CREATION_REVERSAL",
  RETURN_DISPOSITION: "RETURN_DISPOSITION",
  PRODUCT_RESOLUTION_CORRECTION: "PRODUCT_RESOLUTION_CORRECTION",
  CONDITION_CORRECTION: "CONDITION_CORRECTION",
  QUANTITY_CORRECTION: "QUANTITY_CORRECTION",
  RETURN_TO_RETAILER: "RETURN_TO_RETAILER",
  PARTIAL_RETURN: "PARTIAL_RETURN",
  DAMAGED_AFTER_RECEIVING: "DAMAGED_AFTER_RECEIVING",
  WRONG_ITEM_RESOLUTION: "WRONG_ITEM_RESOLUTION",
  SUBSTITUTION_RESOLUTION: "SUBSTITUTION_RESOLUTION",
  REPLACEMENT_RECEIVED: "REPLACEMENT_RECEIVED",
  UNEXPECTED_EXTRA_RESOLUTION: "UNEXPECTED_EXTRA_RESOLUTION",
  ACQUISITION_COST_CORRECTION: "ACQUISITION_COST_CORRECTION",
  REVERSAL_CORRECTION: "REVERSAL_CORRECTION",
});

export const INVENTORY_CREATION_DISPOSITIONS = Object.freeze({
  ADD_TO_INVENTORY: "ADD_TO_INVENTORY",
  ADD_AS_DAMAGED: "ADD_AS_DAMAGED",
  HOLD_FOR_RETURN: "HOLD_FOR_RETURN",
  HOLD_FOR_CLAIM: "HOLD_FOR_CLAIM",
  EXCLUDE: "EXCLUDE",
  UNRESOLVED_EXTRA: "UNRESOLVED_EXTRA",
});

export const INVENTORY_CREATION_CONDITIONS = Object.freeze({
  NEW: "NEW",
  SEALED: "SEALED",
  OPEN_BOX: "OPEN_BOX",
  DAMAGED: "DAMAGED",
  USED: "USED",
  UNKNOWN: "UNKNOWN",
});

export const INVENTORY_CREATION_MATCH_STATES = Object.freeze({
  MATCHED: "MATCHED",
  OWNER_RESOLVED: "OWNER_RESOLVED",
  AMBIGUOUS: "AMBIGUOUS",
  UNRESOLVED: "UNRESOLVED",
});

export const INVENTORY_CREATION_PRODUCT_CLASSIFICATIONS = Object.freeze({
  SEALED_PRODUCT: "Sealed product",
  ACCESSORY: "Accessory",
  RAW_CARD: "Raw card",
  GRADED_CARD: "Graded card",
});

export const INVENTORY_CREATION_ACTIVE_CLASSIFICATIONS = Object.freeze([
  INVENTORY_CREATION_PRODUCT_CLASSIFICATIONS.SEALED_PRODUCT,
  INVENTORY_CREATION_PRODUCT_CLASSIFICATIONS.ACCESSORY,
]);

export const INVENTORY_CREATION_LIMITS = Object.freeze({
  maximumIdentifier: 500,
  maximumLabel: 500,
  maximumQuantity: 1_000_000,
  maximumUnitCosts: 1_000_000,
  maximumReferences: 1_000,
  maximumWarnings: 200,
});

export const INVENTORY_CREATION_SAFETY = Object.freeze({
  authoritative: "LOCAL_ONLY",
  remoteActive: false,
  automaticInventoryCreation: false,
  automaticProductCreation: false,
  ownerConfirmationRequired: true,
  candidatePersisted: false,
  candidateEqualsInventory: false,
  handoffPreviewEqualsInventory: false,
  sourceEvidenceCopied: false,
});
