export const BACKUP_STORAGE_TYPES = Object.freeze({
  LOCAL_STORAGE: "LOCAL_STORAGE",
  SESSION_STORAGE: "SESSION_STORAGE",
  SUPABASE: "SUPABASE",
  POSTGRES: "POSTGRES",
  FILE_REFERENCE: "FILE_REFERENCE",
});

export const LEGACY_CORE_ALLOWLIST = Object.freeze([
  "items",
  "purchasers",
  "tideTradrWatchlist",
  "marketplaceListings",
  "marketplaceReports",
  "marketplaceSavedIds",
  "tideTradrLookupId",
  "marketPriceCache",
  "marketPriceMemories",
  "itemComparisons",
  "vaultCollectionSets",
  "vaultDisplayCase",
  "userSearchAliases",
  "expenses",
  "sales",
  "tradeRecords",
  "trades",
  "sparkGifts",
  "sparkKidPacks",
  "sparkEventPlans",
  "collectorEventPlans",
  "vehicles",
  "mileageTrips",
  "workspaces",
  "activeWorkspaceId",
  "forgeModeSettings",
  "dealForm",
  "homeStatsEnabled",
  "dashboardPreset",
  "dashboardLayout",
  "dashboardCardStyle",
  "appThemeChoice",
  "appSetupPersonalization",
  "cloudSyncPreference",
  "locationSettings",
]);

export const PHASE2_LOCAL_ALLOWLIST = Object.freeze([
  "appPreferences",
  "notificationPreferences",
  "dealFinderSessions",
  "dealFinderItems",
  "scannerIntakeSessions",
  "marketplaceListingChannels",
  "receiptRecords",
  "receiptLineItems",
  "kidCommunityProjects",
  "kidCommunityProjectItems",
  "aiAssistEvents",
  "updatedAt",
]);

const registry = [
  {
    sourceId: "deal-finder",
    displayName: "Deal Finder records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "ember-and-tide.flip-scout.v1",
    schemaVersion: 2,
    supportedSchemaVersions: [1, 2],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "deal-finder-v2",
    recordPaths: ["deals", "appraisals", "auctions", "searchRules", "purchases", "lots", "costAllocations", "inventory", "sales", "returns", "expenses", "mileage", "activity", "providerListings"],
    referenceDependencies: ["legacy-core-business"],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {},
  },
  {
    sourceId: "owner-center",
    displayName: "Owner Center records and controls",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "private-business-hub.owner-center.v1",
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "owner-center-v1",
    recordPaths: ["restockStoreProfiles", "restockEvents", "restockPredictions", "storeVisits", "productObservations", "imports", "jobs"],
    referenceDependencies: ["deal-finder"],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {},
  },
  {
    sourceId: "account-ops",
    displayName: "Account Ops records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "code3.account-ops.v1",
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "account-ops-v1",
    recordPaths: ["profileGroups", "profiles", "emailDomains", "emailAliases", "retailers", "storeAccounts", "tasks", "activity"],
    referenceDependencies: [],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {
      schemaVersion: 1,
      profileGroups: [],
      profiles: [],
      emailDomains: [],
      emailAliases: [],
      retailers: [],
      storeAccounts: [],
      tasks: [],
      activity: [],
    },
  },
  {
    sourceId: "inbox-order-intelligence",
    displayName: "Inbox and Order Intelligence records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "code3.inbox-order.v1",
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "inbox-order-v1",
    recordPaths: ["messageEvents", "orderCandidates", "candidateEvents", "activity"],
    referenceDependencies: ["account-ops"],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {
      schemaVersion: 1,
      updatedAt: "1970-01-01T00:00:00.000Z",
      messageEvents: [],
      orderCandidates: [],
      candidateEvents: [],
      activity: [],
    },
  },
  {
    sourceId: "bot-operations",
    displayName: "Bot Operations records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "code3.bot-ops.v1",
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "bot-operations-v1",
    recordPaths: [
      "installations",
      "retailerAccountLinks",
      "botProfiles",
      "proxyGroups",
      "productTargets",
      "taskGroups",
      "tasks",
      "attempts",
      "checkoutEvidence",
      "activity",
    ],
    referenceDependencies: ["account-ops", "inbox-order-intelligence"],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {
      schemaVersion: 1,
      updatedAt: "1970-01-01T00:00:00.000Z",
      installations: [],
      retailerAccountLinks: [],
      botProfiles: [],
      proxyGroups: [],
      productTargets: [],
      taskGroups: [],
      tasks: [],
      attempts: [],
      checkoutEvidence: [],
      activity: [],
    },
  },
  {
    sourceId: "purchase-receiving",
    displayName: "Purchase and Receiving records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "code3.purchase-receiving.v1",
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "purchase-receiving-v1",
    recordPaths: ["purchaseDrafts", "purchases", "purchaseEvents", "receivingEvents", "activity"],
    referenceDependencies: ["account-ops", "inbox-order-intelligence", "bot-operations"],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {
      schemaVersion: 1,
      updatedAt: "1970-01-01T00:00:00.000Z",
      purchaseDrafts: [],
      purchases: [],
      purchaseEvents: [],
      receivingEvents: [],
      activity: [],
    },
  },
  {
    sourceId: "legacy-core-business",
    displayName: "Legacy collection and business records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "et-tcg-beta-data",
    schemaVersion: 0,
    supportedSchemaVersions: [0],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "allowlisted-json-key",
    validationAdapter: "legacy-core-v0",
    allowedFields: LEGACY_CORE_ALLOWLIST,
    recordPaths: ["items", "purchasers", "tideTradrWatchlist", "marketplaceListings", "marketplaceReports", "marketPriceMemories", "itemComparisons", "vaultCollectionSets", "vaultDisplayCase", "expenses", "sales", "tradeRecords", "trades", "sparkGifts", "sparkKidPacks", "sparkEventPlans", "collectorEventPlans", "vehicles", "mileageTrips", "workspaces"],
    referenceDependencies: ["deal-finder", "phase2-local-fallback"],
    containsSecurityOrSessionState: true,
    affectsCoverage: true,
    emptyValue: {},
  },
  {
    sourceId: "legacy-restock-scout",
    displayName: "Legacy restock and store records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "et-tcg-beta-scout",
    schemaVersion: 0,
    supportedSchemaVersions: [0],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "generic-local-json",
    recordPaths: ["stores", "reports", "tidepoolReports", "tidepoolEvents", "items", "routes", "restockIntel", "restockPatterns", "intelImportReviews", "storeAliases", "bestBuyStockResults", "bestBuyStockHistory", "bestBuyStoreStock", "bestBuyAlerts", "bestBuyNightlyReports"],
    referenceDependencies: ["owner-center"],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {},
  },
  {
    sourceId: "legacy-community",
    displayName: "Legacy private community records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "et-tcg-beta-tidepool",
    schemaVersion: 0,
    supportedSchemaVersions: [0],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "generic-local-json",
    recordPaths: ["posts", "comments", "reactions", "trustedCircle"],
    referenceDependencies: [],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {},
  },
  ...[
    ["legacy-feedback", "Feedback records", "et-tcg-beta-feedback"],
    ["legacy-suggestions", "Correction and suggestion records", "et-tcg-beta-suggestions"],
    ["legacy-admin-review-history", "Administrative review history", "et-tcg-beta-admin-review-log"],
    ["product-sightings", "Product sighting records", "tide_tradr_what_did_i_see_reports"],
  ].map(([sourceId, displayName, storageKey]) => ({
    sourceId,
    displayName,
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey,
    schemaVersion: 0,
    supportedSchemaVersions: [0],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "record-array",
    recordPaths: ["$"],
    referenceDependencies: [],
    containsSecurityOrSessionState: sourceId === "legacy-admin-review-history",
    affectsCoverage: true,
    emptyValue: [],
  })),
  {
    sourceId: "manual-market-price-cache",
    displayName: "Manual and cached price records",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "et-tcg-market-price-cache",
    schemaVersion: 0,
    supportedSchemaVersions: [0],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "generic-local-json",
    recordPaths: ["prices", "failedMatches"],
    referenceDependencies: [],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: {},
  },
  {
    sourceId: "phase2-local-fallback",
    displayName: "Connected-workflow local fallback",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey: "et-tcg-phase2-data",
    schemaVersion: 0,
    supportedSchemaVersions: [0],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "allowlisted-json-key",
    validationAdapter: "phase2-local-v0",
    allowedFields: PHASE2_LOCAL_ALLOWLIST,
    recordPaths: ["dealFinderSessions", "dealFinderItems", "scannerIntakeSessions", "marketplaceListingChannels", "receiptRecords", "receiptLineItems", "kidCommunityProjects", "kidCommunityProjectItems", "aiAssistEvents"],
    referenceDependencies: ["legacy-core-business"],
    containsSecurityOrSessionState: true,
    affectsCoverage: true,
    emptyValue: {},
  },
  ...[
    ["beta-readiness-records", "Beta readiness records", "et-tcg-beta-readiness"],
    ["grade-assist-checklists", "Grading-assistance checklists", "et-grade-assist-checklists"],
    ["assistant-thread", "Business Assistant local thread", "et-ember-assist-thread"],
    ["daily-progress", "Daily progress", "et-tcg-daily-tide"],
  ].map(([sourceId, displayName, storageKey]) => ({
    sourceId,
    displayName,
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKey,
    schemaVersion: 0,
    supportedSchemaVersions: [0],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "json-key",
    validationAdapter: "generic-local-json",
    recordPaths: ["$"],
    referenceDependencies: [],
    containsSecurityOrSessionState: false,
    affectsCoverage: true,
    emptyValue: sourceId === "assistant-thread" ? [] : {},
  })),
  {
    sourceId: "safe-ui-preferences",
    displayName: "Safe local display preferences",
    storageType: BACKUP_STORAGE_TYPES.LOCAL_STORAGE,
    storageKeys: [
      "et-tcg-app-theme",
      "et-tcg-beta-catalog-view",
      "et-tcg-beta-catalog-page-size",
      "et-tcg-beta-vault-showcase-view",
      "et-tcg-forge-mode-settings",
      "autoOpenDropWebsite",
      "code3.workspace-preference.v1",
    ],
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "exact-key-group",
    validationAdapter: "safe-preferences-v1",
    recordPaths: [],
    referenceDependencies: [],
    containsSecurityOrSessionState: false,
    affectsCoverage: false,
    emptyValue: {},
  },
  {
    sourceId: "workflow-drafts",
    displayName: "Unsaved workflow drafts",
    storageType: BACKUP_STORAGE_TYPES.SESSION_STORAGE,
    storageKeys: ["private-business-hub.deal-analysis-draft.v1"],
    storagePrefixes: ["private-business-hub.form-draft."],
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: true,
    exportAdapter: "safe-session-key-group",
    validationAdapter: "workflow-drafts-v1",
    recordPaths: [],
    referenceDependencies: [],
    containsSecurityOrSessionState: false,
    affectsCoverage: false,
    emptyValue: {},
  },
  {
    sourceId: "supabase-owner-data",
    displayName: "Supabase owner records",
    storageType: BACKUP_STORAGE_TYPES.SUPABASE,
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: false,
    exportAdapter: null,
    validationAdapter: "server-source-manifest",
    recordPaths: [],
    referenceDependencies: ["phase2-local-fallback", "legacy-core-business"],
    containsSecurityOrSessionState: true,
    affectsCoverage: "when-configured",
    exclusionReason: "Legacy Supabase owner records are not included by the canonical server-export adapter and require a separate owner-authorized export contract.",
  },
  {
    sourceId: "postgres-owner-data",
    displayName: "PostgreSQL and Express owner records",
    storageType: BACKUP_STORAGE_TYPES.POSTGRES,
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: false,
    exportAdapter: null,
    validationAdapter: "server-source-manifest",
    recordPaths: ["records"],
    referenceDependencies: ["legacy-core-business"],
    containsSecurityOrSessionState: false,
    affectsCoverage: "when-configured",
    exclusionReason: "Canonical PostgreSQL records are included only when the owner-authorized server export is available; legacy PostgreSQL and process-memory records remain outside that contract.",
  },
  {
    sourceId: "file-assets",
    displayName: "Receipt, listing, and product files",
    storageType: BACKUP_STORAGE_TYPES.FILE_REFERENCE,
    schemaVersion: 1,
    supportedSchemaVersions: [1],
    containsOwnerData: true,
    includedInPhase1AExport: false,
    exportAdapter: null,
    validationAdapter: "file-reference-manifest",
    recordPaths: [],
    referenceDependencies: ["phase2-local-fallback", "deal-finder", "legacy-core-business"],
    containsSecurityOrSessionState: false,
    affectsCoverage: "when-referenced",
    exclusionReason: "The current backup records file references but does not embed or download file bytes.",
  },
  {
    sourceId: "authentication-state",
    displayName: "Authentication and session persistence",
    storageType: BACKUP_STORAGE_TYPES.SESSION_STORAGE,
    schemaVersion: 0,
    supportedSchemaVersions: [],
    containsOwnerData: false,
    includedInPhase1AExport: false,
    exportAdapter: null,
    validationAdapter: null,
    recordPaths: [],
    referenceDependencies: [],
    containsSecurityOrSessionState: true,
    affectsCoverage: false,
    exclusionReason: "Authentication tokens, browser sessions, invitation tokens, and impersonation state are prohibited in backups.",
  },
];

export const BACKUP_SOURCE_REGISTRY = Object.freeze(registry.map((source) => Object.freeze({ ...source })));

export function getBackupSource(sourceId, sourceRegistry = BACKUP_SOURCE_REGISTRY) {
  return sourceRegistry.find((source) => source.sourceId === sourceId) || null;
}

export function isSourceCoverageRelevant(source, context = {}) {
  if (source.affectsCoverage === true) return true;
  if (source.affectsCoverage === "when-configured") {
    return new Set(context.configuredSourceIds || []).has(source.sourceId);
  }
  if (source.affectsCoverage === "when-referenced") return Boolean(context.hasFileReferences);
  return false;
}
